In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("iris.data")

In [4]:
data.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
X = data.iloc[:, :-1].values
print(X)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [10]:
y = data.iloc[:, -1].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       '

In [11]:
from sklearn.model_selection import train_test_split


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [14]:
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.8 2.7 4.1 1. ]
 [4.9 3.  1.4 0.2]
 [5.8 2.7 5.1 1.9]
 [6.2 2.2 4.5 1.5]
 [4.7 3.2 1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [4.8 3.  1.4 0.3]
 [5.9 3.  4.2 1.5]
 [6.3 2.7 4.9 1.8]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [4.8 3.4 1.9 0.2]
 [5.6 2.7 4.2 1.3]
 [5.  3.5 1.3 0.3]
 [5.7 3.  4.2 1.2]
 [6.9 3.1 5.4 2.1]
 [5.3 3.7 1.5 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [4.9 3.1 1.5 0.1]
 [5.7 2.8 4.1 1.3]
 [6.3 2.5 5.  1.9]
 [6.1 2.9 4.7 1.4]
 [6.  3.4 4.5 1.6]
 [6.9 3.2 5.7 2.3]
 [6.5 2.8 4.6 1.5]
 [4.6 3.4 1.4 0.3]
 [6.2 3.4 5.4 2.3]
 [6.  3.  4.8 1.8]
 [7.  3.2 4.7 1.4]
 [5.5 3.5 1.3 0.2]
 [5.5 2.4 3.7 1. ]
 [6.  2.9 4.5 1.5]
 [5.  3.2 1.2 0.2]
 [5.8 2.8 5.1 2.4]
 [4.4 2.9 1.4 0.2]
 [5.1 3.8 1.9 0.4]
 [6.1 2.8 4.  1.3]
 [5.1 2.5 3.  1.1]
 [5.4 3.  4.5 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [5.5 2.6 4.4 1.2]
 [4.9 3.1 1.5 0.1]
 [5.8 4.  1.2 0.2]
 [6.  2.2 5.  1.5]
 [6.1 3.  4.9 1.8]
 [5.  3.6 1.4 0.2]
 [5.7 3.8 1.7 0.3]
 [5.1 3.4 1.5 0.2]
 [6.1 2.8 4.

In [15]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [16]:
prediction = lr.predict(X_test)

In [17]:
print(prediction)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-virginica']


In [18]:
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, prediction))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.92      0.80      0.86        15
 Iris-virginica       0.83      0.94      0.88        16

       accuracy                           0.92        50
      macro avg       0.92      0.91      0.91        50
   weighted avg       0.92      0.92      0.92        50



In [20]:
print(confusion_matrix(y_test, prediction))

[[19  0  0]
 [ 0 12  3]
 [ 0  1 15]]
