#  NumPy 

Numpy is a linear algebra library for python 

# NumPy arrays 

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list) #casts the list to array 

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
arry = np.array(my_mat)

In [7]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10) #

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2) #step 2s, thats every next second value 

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3) #will give the output of one row and three columns (all the output will be in 0's)

array([0., 0., 0.])

In [12]:
np.zeros((3,4)) #if we pass in tuple, the first 3 acts as row and  4    acts as column (a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones(4) #here the outputs will be in ones and the 1 row and 4 columns 

array([1., 1., 1., 1.])

In [14]:
#linspace will give output of the n number of evenly spaced points between the asked numbers

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,4,10) 

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [17]:
#np.eye(n) will create n*n diagonal matrix 

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#there is a  method for getting the the random numbers 

In [20]:
np.random.rand(5)

array([0.67296037, 0.71160864, 0.19409052, 0.84349067, 0.41214946])

In [21]:
#for 5*5 matrix

In [22]:
np.random.rand(5,5)

array([[0.5395597 , 0.79795921, 0.37648835, 0.52353798, 0.38379849],
       [0.34969266, 0.31659941, 0.65651594, 0.56122897, 0.90252232],
       [0.92459879, 0.46546585, 0.42524042, 0.05073146, 0.86855394],
       [0.36316578, 0.21143251, 0.64127483, 0.83168607, 0.08721045],
       [0.11589856, 0.42565748, 0.65737364, 0.81248743, 0.75628114]])

In [23]:
#If we want a sample or a many samples from standard normal or gaussian  normal ,use randn 

In [24]:
np.random.randn(1)

array([-0.95178775])

In [25]:
np.random.randn(2)

array([2.45727376, 0.87254972])

In [26]:
np.random.randn(3)

array([ 1.01823637, -0.3084862 ,  0.59364615])

In [27]:
np.random.randn(4,4)

array([[ 1.33003659, -0.65694406,  0.256905  ,  0.84910424],
       [-0.88512363, -0.7570616 , -0.11297058,  0.95593976],
       [ 0.41284703, -0.50575979, -0.4415712 ,  0.34030637],
       [-0.21125273, -2.25233848,  0.60425343, -1.00090835]])

In [28]:
#randint : used for getting the random integer from low to high 

In [29]:
np.random.randint(1,100)

40

In [30]:
np.random.randint(1,100,10) #for 10 random integers 

array([97, 87, 83, 66, 31, 12, 67, 47, 43, 12])

In [31]:
arr = np.arange(36)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [33]:
ranarr = np.random.randint(0,50,10)

In [46]:
ranarr

array([22, 46, 27, 33, 32, 32, 20, 14, 30, 36])

In [67]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [34]:
ranarr

array([16,  1, 49,  9, 40, 16,  4, 28, 43, 25])

In [35]:
ranarr.max()

49

In [36]:
ranarr.min()

1

In [37]:
#for the index location of max value 
ranarr.argmax()


2

In [38]:
ranarr.argmin()

1

In [50]:
arr.shape #here (25,) denotes one dimensioaal 

(25,)

In [68]:
arr = arr.reshape(6,6)

In [69]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [70]:
arr.shape

(6, 6)

In [71]:
arr.dtype

dtype('int32')

In [73]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])